# Site settings
title: Lauren Portfolio
email: l.hutson@live.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl:
url:

# User setting
owner:
email: l.hutson@live.com
facebook_username:
twitter_username:
github_username: laurenhut
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone: 773-576-5666
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
